### ISSUE TITLE
Unable to inject service

### ISSUE THREAD

**Issue by mrzacarias** [jasonkriss/ember-cli-intercom#1]
Hello, I need a help here...

After installing your addon, I tried to inject this service on the application route:

``` javascript
  intercom: Ember.inject.service('intercom'),
```

But I always get this error:

``` javascript
Cannot read property 'service' of undefined
```

What I'm doing wrong here?

Thanks

**Comment by jasonkriss** [comment]
hey @mrzacarias. Can you post more of your code? The error looks like it is saying `Ember` does not exist in the current context.

**Comment by mrzacarias** [comment]
Hi, Jason, sorry for the long time with no answer.

That was a problem on my local ember, now it's ok.

**Comment by jasonkriss** [comment]
np @mrzacarias. Thanks for following up!
